### ISSUE TITLE
Loop instructions have incorrect example

### ISSUE THREAD

**Issue by snackattas** [denysdovhan/learnyoubash#13]
Here are the instructions for loops.  They are incorrect because the exercise is to write even numbers, but the example is outputting odd numbers.  In addition, it says to write the numbers in range between the first and second parameters.  But the example includes 17, which is not between the first and second parameters.  It's confusing if the exercise is to write an inclusive or exclusive list

```
Create a file named loops.bash.

The first two positional parameters which will be passed into your script are the limits. 
You should write all even numbers in range between the first and second positional parameters.

Example:

./loops.bash 10 17

 Output:

 11
 13
 15
 17
```

**Comment by denysdovhan** [comment]
This problem was fixed in version `v1.1.1`. Please update your installation using:

``` sh
npm i -g learnyoubash
```
