### ISSUE TITLE
Incorrect Footer instruction 

### ISSUE THREAD

**Issue by ragmha** [denysdovhan/learnyoubash#17]
![wrong](https://cloud.githubusercontent.com/assets/6115991/17646286/1398c280-61cc-11e6-9dc6-379fe3319214.png)

`learnyoubash.js` seems to be using `workshopper-adventure/default/footer`, it should instead use `i18n/footer` to display the below output

![wrong2](https://cloud.githubusercontent.com/assets/6115991/17646303/80128270-61cc-11e6-9742-59c7f5f30875.png)

**Comment by denysdovhan** [comment]
Nice catch, thank you!
Published as `v1.1.13`!
