### ISSUE TITLE
Fix English in functions

### ISSUE THREAD

**Issue by ericat** [denysdovhan/learnyoubash#24]
Also possibly not a great idea to intro recursion in a basic bash course?

Thoughts? Thank you.

**Comment by denysdovhan** [comment]
Yeah, I had some feedback from users that it's a bit difficult to understand. But, in other hand, recursion is a basic thing in programming. A lot of developers told me that it's a good idea to explain how it works in shell scripting. Thus, I am not going to remove this exercise.

If you have difficulties with that exercise, I will be grateful if you would propose how I can explain recursion easier.

**Comment by ericat** [comment]
Hi! My apologies for not being clear, the recursion is not an issue, just a thought. 
I suggest perhaps having a native speaker going over the description?

**Comment by denysdovhan** [comment]
@Ericat maybe it'd be better. Can you suggest someone?

**Comment by ericat** [comment]
yes! Give me a couple of days :)

**Comment by denysdovhan** [comment]
@Ericat okay :) don't forget to open pr!

**Comment by ericat** [comment]
This has been done <3
