### ISSUE TITLE
Solutions not being printed to screen

### ISSUE THREAD

**Issue by newswim** [denysdovhan/learnyoubash#39]
Hi! I really like what you've done with this workshopper!!

It seems like the output is a little funky on my machine,

<img width="649" alt="screen shot 2016-11-28 at 9 47 04 am" src="https://cloud.githubusercontent.com/assets/6667096/20675453/ecd67834-b551-11e6-84c6-ac7f7be74b99.png">

I've only completed up to Positional Parameters, but that output seemed uniform up to this point. I'm willing to investigate further.

I noticed that the solution was in a separate markdown file that doesn't seem to get included. Might indicate something?

MacOS / iTerm 2

**Comment by denysdovhan** [comment]
@martinheidegger could you help me here? What the API should I use to provide official solutions for users?

**Comment by martinheidegger** [comment]
@denysdovhan Seems like the solution file was somehow missing from the solution output. PR #42 should fix that.

**Comment by denysdovhan** [comment]
@martinheidegger okay, thank you! Checking this out. BTW, i had the same problem with _how-to-markdown_ workshopper.

**Comment by denysdovhan** [comment]
Thank you @newswim for reporting!
Published as `v1.3.1`!
