### ISSUE TITLE
Windows 10 "check for update" throws errors

### ISSUE THREAD

**Issue by NickParks** [denysdovhan/learnyoubash#5]
Clicking the "Check for update" option seems to throw the error below.

![another error](https://cloud.githubusercontent.com/assets/5506537/13204390/df8aabba-d883-11e5-8b6d-1f6b41613bf9.PNG)

However upon manually executing the command it seems to have worked
![it worked](https://cloud.githubusercontent.com/assets/5506537/13204399/fb3f05e0-d883-11e5-8030-5c6e27e3be9f.PNG)

**Comment by denysdovhan** [comment]
I think this is a problem with workshopper-adventure.

**Comment by martinheidegger** [comment]
@SirNickParks Would you mind to run `where npm` ?

**Comment by NickParks** [comment]
@martinheidegger 

```
$ where npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
```

**Comment by martinheidegger** [comment]
Okay, thanks. I can confirm its a bug in workshopper-adventure. will continue in https://github.com/workshopper/workshopper-adventure/issues/47

**Comment by denysdovhan** [comment]
Duplicate of workshopper/workshopper-adventure#47
