### ISSUE TITLE
Debugging challenge suggested solution

### ISSUE THREAD

**Issue by ghost** [denysdovhan/learnyoubash#7]
The suggested solution for the debugging challenge is weird (or the challenge itself should be better phrased).

The challenge says: "You will receive positional parameters. These positional parameters are filenames."

&

"Create all these files"

The suggested solution contains the `mv file*` command. While this is indeed a good solution, there was no way of knowing that the files would be named in the file\* format, thus using `mv file*` is a big assumption.

**Comment by denysdovhan** [comment]
Thank you for feedback!

I know about it and I'm gonna fix this. I've made this mistake in the problem. As you may notice [here](https://github.com/denysdovhan/learnyoubash/blob/master/exercises/debugging/exercise.js#L9), this exercise passes to problem filenames in format `file[random]`. That why the solution contains `mv file*` statement.
